master:
  address: "ec2-43-199-45-127.ap-east-1.compute.amazonaws.com"
  user: "ubuntu"
  identity_file: "~/roxwell.pem"
  config_path: "local.conf"
  protocol: "paxos"

servers:
  - address: "ec2-16-163-40-158.ap-east-1.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/roxwell.pem"
    config_path: "local.conf"
    alias: "server-1"
    protocol: "paxos"
  - address: "ec2-43-199-147-111.ap-east-1.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/roxwell.pem"
    config_path: "local.conf"
    alias: "server-2"
    protocol: "paxos"

clients:
  - address: "ec2-18-167-94-16.ap-east-1.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/roxwell.pem"
    config_path: "local.conf"
    alias: "client"

repo_url: "https://github.com/JamesLiu12/PPaxos"
repo_path: "~/PPaxos/"
working_dir: "~/PPaxos/swiftpaxos/"
nfs_server_path: "/exports/paxos"
nfs_client_path: "/mnt/nfs/paxos"
test_name: "conflict0"