master:
  address: "ec2-54-46-49-81.ap-east-1.compute.amazonaws.com"
  user: "ubuntu"
  identity_file: "~/pem/m/roxwell.pem"
  config_path: "local.conf"

servers:
  - address: "ec2-54-252-165-236.ap-southeast-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k1/roxwell.pem"
    config_path: "local.conf"
    alias: "server-1"
  - address: "ec2-43-201-77-75.ap-northeast-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k2/roxwell.pem"
    config_path: "local.conf"
    alias: "server-2"
  - address: "ec2-18-60-149-3.ap-south-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k3/roxwell.pem"
    config_path: "local.conf"
    alias: "server-3"
  - address: "ec2-18-237-250-153.us-west-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k4/roxwell.pem"
    config_path: "local.conf"
    alias: "server-4"
  - address: "ec2-51-34-20-118.eu-central-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k5/roxwell.pem"
    config_path: "local.conf"
    alias: "server-5"

clients:
  - address: "ec2-3-25-82-225.ap-southeast-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k1/roxwell.pem"
    config_path: "local.conf"
    alias: "client-1"
  - address: "ec2-13-125-75-59.ap-northeast-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k2/roxwell.pem"
    config_path: "local.conf"
    alias: "client-2"
  - address: "ec2-18-60-247-43.ap-south-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k3/roxwell.pem"
    config_path: "local.conf"
    alias: "client-3"
  - address: "ec2-34-210-214-119.us-west-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k4/roxwell.pem"
    config_path: "local.conf"
    alias: "client-4"
  - address: "ec2-51-34-46-237.eu-central-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k5/roxwell.pem"
    config_path: "local.conf"
    alias: "client-5"

repo_url: "https://github.com/JamesLiu12/PPaxos"
repo_path: "~/PPaxos/"
working_dir: "~/PPaxos/swiftpaxos/"
nfs_server_path: "/exports/paxos"
nfs_client_path: "/mnt/nfs/paxos"
test_name: "conflict-90"
protocol: "eppaxos"