master:
  address: "ec2-95-40-97-183.ap-east-1.compute.amazonaws.com"
  user: "ubuntu"
  identity_file: "~/pem/m/roxwell.pem"
  config_path: "local.conf"

servers:
  - address: "ec2-13-55-245-34.ap-southeast-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k1/roxwell.pem"
    config_path: "local.conf"
    alias: "server-1"
  - address: "ec2-13-124-23-155.ap-northeast-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k2/roxwell.pem"
    config_path: "local.conf"
    alias: "server-2"
  - address: "ec2-18-61-230-252.ap-south-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k3/roxwell.pem"
    config_path: "local.conf"
    alias: "server-3"
  - address: "ec2-44-254-80-44.us-west-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k4/roxwell.pem"
    config_path: "local.conf"
    alias: "server-4"
  - address: "ec2-51-34-37-0.eu-central-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k5/roxwell.pem"
    config_path: "local.conf"
    alias: "server-5"

clients:
  - address: "ec2-52-65-133-35.ap-southeast-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k1/roxwell.pem"
    config_path: "local.conf"
    alias: "client-1"
  - address: "ec2-13-124-2-229.ap-northeast-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k2/roxwell.pem"
    config_path: "local.conf"
    alias: "client-2"
  - address: "ec2-18-61-230-152.ap-south-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k3/roxwell.pem"
    config_path: "local.conf"
    alias: "client-3"
  - address: "ec2-44-247-21-202.us-west-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k4/roxwell.pem"
    config_path: "local.conf"
    alias: "client-4"
  - address: "ec2-16-63-22-168.eu-central-2.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/pem/k5/roxwell.pem"
    config_path: "local.conf"
    alias: "client-5"

repo_url: "https://github.com/JamesLiu12/PPaxos"
repo_path: "~/PPaxos/"
working_dir: "~/PPaxos/swiftpaxos/"
nfs_server_path: "/exports/paxos"
nfs_client_path: "/mnt/nfs/paxos"
test_name: "conflict-0"
protocol: "epaxos"