master:
  address: "ec2-16-162-34-165.ap-east-1.compute.amazonaws.com"
  user: "ubuntu"
  identity_file: "~/roxwell.pem"
  config_path: "local.conf"

servers:
  - address: "ec2-54-46-70-75.ap-east-1.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/roxwell.pem"
    config_path: "local.conf"
    alias: "server-1"
  - address: "ec2-95-40-94-209.ap-east-1.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/roxwell.pem"
    config_path: "local.conf"
    alias: "server-2"
  - address: "ec2-43-199-71-207.ap-east-1.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/roxwell.pem"
    config_path: "local.conf"
    alias: "server-3"

clients:
  - address: "ec2-54-46-77-0.ap-east-1.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/roxwell.pem"
    config_path: "local.conf"
    alias: "client-1"
  - address: "ec2-54-46-106-226.ap-east-1.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/roxwell.pem"
    config_path: "local.conf"
    alias: "client-2"
  - address: "ec2-16-162-217-223.ap-east-1.compute.amazonaws.com"
    user: "ubuntu"
    identity_file: "~/roxwell.pem"
    config_path: "local.conf"
    alias: "client-3"

repo_url: "https://github.com/JamesLiu12/PPaxos"
repo_path: "~/PPaxos/"
working_dir: "~/PPaxos/swiftpaxos/"
nfs_server_path: "/exports/paxos"
nfs_client_path: "/mnt/nfs/paxos"
test_name: "conflict-0"
protocol: "epaxos"